'use client'

import { useState, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Calculator, Share2, Code, Info, ExternalLink, Mail, DollarSign, TrendingDown } from 'lucide-react'

function CalculatorContent() {
  const searchParams = useSearchParams()

  // Initialize from URL params if available
  const [insuredValue, setInsuredValue] = useState('')
  const [deductiblePercent, setDeductiblePercent] = useState('')
  const [standardDeductible, setStandardDeductible] = useState('1000')
  const [annualPremium, setAnnualPremium] = useState('3500')
  const [deductibleAmount, setDeductibleAmount] = useState(0)
  const [showShareDialog, setShowShareDialog] = useState(false)
  const [showEmbedDialog, setShowEmbedDialog] = useState(false)
  const [showEmailDialog, setShowEmailDialog] = useState(false)
  const [email, setEmail] = useState('')
  const [emailSent, setEmailSent] = useState(false)

  // Load URL params on mount
  useEffect(() => {
    const valueParam = searchParams.get('value')
    const percentParam = searchParams.get('deductible')
    const standardParam = searchParams.get('standard')
    const premiumParam = searchParams.get('premium')

    setInsuredValue(valueParam || '300000')
    setDeductiblePercent(percentParam || '5')
    if (standardParam) setStandardDeductible(standardParam)
    if (premiumParam) setAnnualPremium(premiumParam)
  }, [searchParams])

  useEffect(() => {
    const value = parseFloat(insuredValue.replace(/,/g, '')) || 0
    const percent = parseFloat(deductiblePercent) || 0
    const calculated = (value * percent) / 100
    setDeductibleAmount(calculated)
  }, [insuredValue, deductiblePercent])

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value)
  }

  const handleInsuredValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/[^0-9]/g, '')
    setInsuredValue(value)
  }

  const scenarios = [
    { damage: 5000, label: 'Minor damage' },
    { damage: deductibleAmount * 0.5, label: 'Below deductible' },
    { damage: deductibleAmount * 2, label: 'Moderate damage' },
    { damage: deductibleAmount * 5, label: 'Severe damage' },
    { damage: parseFloat(insuredValue.replace(/,/g, '')) || 0, label: 'Total loss' },
  ]

  // Generate shareable URL with current values
  const generateShareUrl = () => {
    const params = new URLSearchParams({
      value: insuredValue.replace(/,/g, ''),
      deductible: deductiblePercent,
      standard: standardDeductible.replace(/,/g, ''),
      premium: annualPremium.replace(/,/g, ''),
    })
    return `https://www.myyachtsinsurance.com/tools/named-storm-deductible-calculator?${params.toString()}`
  }

  const shareUrl = generateShareUrl()
  const embedCode = `<iframe src="${shareUrl}" width="100%" height="800" frameborder="0"></iframe>`

  // Premium trade-off calculations
  const calculatePremiumTradeoff = () => {
    const currentPremium = parseFloat(annualPremium.replace(/,/g, '')) || 0
    const lowerDeductiblePercent = Math.max(2, parseFloat(deductiblePercent) - 1)
    const premiumIncrease = currentPremium * 0.15 // ~15% increase per 1% deductible reduction
    const newPremium = currentPremium + premiumIncrease
    const value = parseFloat(insuredValue.replace(/,/g, '')) || 0
    const lowerDeductibleAmount = (value * lowerDeductiblePercent) / 100
    const savingsPerClaim = deductibleAmount - lowerDeductibleAmount
    const breakEvenYears = premiumIncrease / savingsPerClaim

    return {
      lowerDeductiblePercent,
      lowerDeductibleAmount,
      newPremium,
      premiumIncrease,
      savingsPerClaim,
      breakEvenYears: isFinite(breakEvenYears) ? breakEvenYears : 0,
    }
  }

  const tradeoff = calculatePremiumTradeoff()

  // Email results function
  const sendEmailResults = () => {
    if (!email || !email.includes('@')) {
      alert('Please enter a valid email address')
      return
    }

    const subject = encodeURIComponent('Your Named Storm Deductible Calculation')
    const body = encodeURIComponent(`Named Storm Deductible Calculator Results

Insured Value: ${formatCurrency(parseFloat(insuredValue.replace(/,/g, '')) || 0)}
Named Storm Deductible: ${deductiblePercent}%
Your Deductible Amount: ${formatCurrency(deductibleAmount)}

Standard Deductible: ${formatCurrency(parseFloat(standardDeductible.replace(/,/g, '')) || 0)}
Deductible Difference: ${formatCurrency(deductibleAmount - (parseFloat(standardDeductible.replace(/,/g, '')) || 0))}

View your full calculation: ${shareUrl}

---
Generated by MyYachtsInsurance.com
`)

    window.location.href = `mailto:${email}?subject=${subject}&body=${body}`
    setEmailSent(true)
    setTimeout(() => {
      setShowEmailDialog(false)
      setEmailSent(false)
    }, 2000)
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      {/* Breadcrumbs */}
      <nav className="text-sm text-muted-foreground mb-4">
        <Link href="/" className="hover:text-foreground">Home</Link>
        <span className="mx-2">/</span>
        <Link href="/yacht-insurance" className="hover:text-foreground">Yacht Insurance</Link>
        <span className="mx-2">/</span>
        <span>Named Storm Deductible Calculator</span>
      </nav>

      {/* Schema Markup for SEO */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Named Storm Deductible Calculator",
            "description": "Free calculator for yacht insurance named storm deductibles in Florida. Calculate hurricane deductibles, compare with standard deductibles, analyze premium trade-offs, and share results.",
            "applicationCategory": "FinanceApplication",
            "operatingSystem": "Web",
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            },
            "featureList": [
              "Calculate percentage-based hurricane deductibles",
              "Compare named storm vs standard deductibles",
              "Premium trade-off analysis with break-even calculations",
              "Email results to yourself",
              "Share calculations via URL",
              "Embed on your website",
              "5 damage scenario analysis"
            ],
            "screenshot": "https://www.myyachtsinsurance.com/tools/named-storm-deductible-calculator",
            "author": {
              "@type": "Organization",
              "name": "MyYachtsInsurance.com"
            },
            "aggregateRating": {
              "@type": "AggregateRating",
              "ratingValue": "5",
              "ratingCount": "1",
              "bestRating": "5",
              "worstRating": "1"
            }
          })
        }}
      />

      {/* FAQ Schema for Premium Trade-off */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
              {
                "@type": "Question",
                "name": "Should I lower my named storm deductible?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Lowering your deductible typically increases your annual premium by ~15% per 1% deductible reduction. You should calculate the break-even point: if hurricanes in your area occur less frequently than your break-even years, keeping a higher deductible is usually more cost-effective. Use our calculator's premium trade-off feature to see your specific numbers."
                }
              },
              {
                "@type": "Question",
                "name": "How much higher is a named storm deductible vs standard deductible?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Named storm deductibles are typically 5-15x higher than standard deductibles because they're percentage-based (2-10% of insured value) rather than flat amounts. For a $300,000 yacht with a 5% storm deductible and $1,000 standard deductible, you'd pay $15,000 for hurricane damage vs $1,000 for non-storm damage."
                }
              },
              {
                "@type": "Question",
                "name": "Can I share my named storm deductible calculation?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Yes, our calculator generates shareable URLs that pre-fill all your values. You can also email results to yourself or embed the calculator on your website using the provided code."
                }
              }
            ]
          })
        }}
      />

      {/* Header */}
      <header className="text-center mb-8">
        <div className="flex justify-center mb-4">
          <Calculator className="h-12 w-12 text-primary" />
        </div>
        <h1 className="text-4xl font-bold mb-4">Named Storm Deductible Calculator</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Calculate your exact hurricane deductible for Florida yacht insurance. Compare deductibles, analyze premium trade-offs, and share results.
        </p>
      </header>

      <div className="grid lg:grid-cols-2 gap-8 mb-12">
        {/* Calculator Input */}
        <Card>
          <CardHeader>
            <CardTitle>Your Policy Details</CardTitle>
            <CardDescription>
              Enter your yacht's insured value and named storm deductible percentage
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <Label htmlFor="insured-value" className="text-base mb-2 block">
                Insured Value
              </Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input
                  id="insured-value"
                  type="text"
                  value={insuredValue ? parseInt(insuredValue).toLocaleString() : ''}
                  onChange={handleInsuredValueChange}
                  placeholder="300,000"
                  className="pl-8 text-lg"
                />
              </div>
              <p className="text-sm text-muted-foreground mt-1">
                The agreed value or ACV on your policy
              </p>
            </div>

            <div>
              <Label htmlFor="deductible-percent" className="text-base mb-2 block">
                Named Storm Deductible Percentage
              </Label>
              <div className="relative">
                <Input
                  id="deductible-percent"
                  type="number"
                  min="0"
                  max="100"
                  step="0.5"
                  value={deductiblePercent}
                  onChange={(e) => setDeductiblePercent(e.target.value)}
                  placeholder="5"
                  className="pr-8 text-lg"
                />
                <span className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">%</span>
              </div>
              <p className="text-sm text-muted-foreground mt-1">
                Typically 2-10% in Florida (check your policy)
              </p>
            </div>

            <div>
              <Label htmlFor="standard-deductible" className="text-base mb-2 block">
                Standard Deductible (Optional)
              </Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input
                  id="standard-deductible"
                  type="text"
                  value={standardDeductible ? parseInt(standardDeductible).toLocaleString() : ''}
                  onChange={(e) => {
                    const value = e.target.value.replace(/[^0-9]/g, '')
                    setStandardDeductible(value)
                  }}
                  placeholder="1,000"
                  className="pl-8 text-lg"
                />
              </div>
              <p className="text-sm text-muted-foreground mt-1">
                Your non-storm deductible for comparison
              </p>
            </div>

            <div className="pt-4 border-t">
              <div className="flex justify-between items-center mb-2">
                <span className="text-lg font-medium">Named Storm Deductible:</span>
              </div>
              <div className="text-4xl font-bold text-primary">
                {formatCurrency(deductibleAmount)}
              </div>
              <p className="text-sm text-muted-foreground mt-2">
                This is what you pay out-of-pocket when a hurricane hits
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Results & Scenarios */}
        <Card>
          <CardHeader>
            <CardTitle>Damage Scenarios</CardTitle>
            <CardDescription>
              How your deductible affects different types of hurricane damage
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {scenarios.filter(s => s.damage > 0).map((scenario, index) => {
                const youPay = Math.min(scenario.damage, deductibleAmount)
                const insurancePays = Math.max(0, scenario.damage - deductibleAmount)

                return (
                  <div key={index} className="border rounded-lg p-4">
                    <div className="font-semibold mb-2">{scenario.label}</div>
                    <div className="grid grid-cols-2 gap-2 text-sm">
                      <div>
                        <div className="text-muted-foreground">Total Damage:</div>
                        <div className="font-medium">{formatCurrency(scenario.damage)}</div>
                      </div>
                      <div>
                        <div className="text-muted-foreground">You Pay:</div>
                        <div className="font-medium text-red-600">{formatCurrency(youPay)}</div>
                      </div>
                      <div className="col-span-2">
                        <div className="text-muted-foreground">Insurance Pays:</div>
                        <div className="font-medium text-green-600">{formatCurrency(insurancePays)}</div>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Dual Deductible Comparison */}
      <Card className="mb-8 border-2 border-primary">
        <CardHeader>
          <div className="flex items-center gap-2">
            <TrendingDown className="h-6 w-6 text-primary" />
            <CardTitle>Storm vs Standard Deductible Comparison</CardTitle>
          </div>
          <CardDescription>
            See how your named storm deductible compares to your regular deductible
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="border rounded-lg p-4 bg-muted/50">
              <div className="text-sm text-muted-foreground mb-1">Standard Deductible</div>
              <div className="text-3xl font-bold mb-2">
                {formatCurrency(parseFloat(standardDeductible.replace(/,/g, '')) || 0)}
              </div>
              <p className="text-sm text-muted-foreground">
                Applied to non-storm damage (grounding, collision, fire, etc.)
              </p>
            </div>
            <div className="border rounded-lg p-4 bg-primary/5">
              <div className="text-sm text-muted-foreground mb-1">Named Storm Deductible</div>
              <div className="text-3xl font-bold text-primary mb-2">
                {formatCurrency(deductibleAmount)}
              </div>
              <p className="text-sm text-muted-foreground">
                Applied only when damage occurs during a named tropical storm/hurricane
              </p>
            </div>
          </div>
          <div className="mt-6 p-4 bg-yellow-50 dark:bg-yellow-950 rounded-lg">
            <div className="flex items-start gap-2">
              <Info className="h-5 w-5 text-yellow-600 mt-0.5 flex-shrink-0" />
              <div>
                <p className="font-semibold text-sm mb-1">Why the difference?</p>
                <p className="text-sm text-muted-foreground">
                  Named storm deductibles are typically {
                    deductibleAmount > 0 && parseFloat(standardDeductible.replace(/,/g, '')) > 0
                      ? `${((deductibleAmount / parseFloat(standardDeductible.replace(/,/g, ''))) - 1).toFixed(0)}x higher`
                      : 'much higher'
                  } because hurricane damage is more expensive and frequent in Florida waters.
                  Your policy has different deductibles for different types of claims.
                </p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Premium Trade-off Calculator */}
      <Card className="mb-8 border-2 border-green-200 dark:border-green-800">
        <CardHeader>
          <div className="flex items-center gap-2">
            <DollarSign className="h-6 w-6 text-green-600" />
            <CardTitle>Should You Lower Your Deductible?</CardTitle>
          </div>
          <CardDescription>
            Calculate whether paying higher premiums for a lower deductible makes financial sense
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div>
              <Label htmlFor="annual-premium" className="text-base mb-2 block">
                Current Annual Premium
              </Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
                <Input
                  id="annual-premium"
                  type="text"
                  value={annualPremium ? parseInt(annualPremium).toLocaleString() : ''}
                  onChange={(e) => {
                    const value = e.target.value.replace(/[^0-9]/g, '')
                    setAnnualPremium(value)
                  }}
                  placeholder="3,500"
                  className="pl-8"
                />
              </div>
              <p className="text-sm text-muted-foreground mt-1">
                Your total yearly premium (check your policy or invoice)
              </p>
            </div>

            <div className="border rounded-lg p-4 bg-muted/50">
              <h4 className="font-semibold mb-3">If you lowered your deductible to {tradeoff.lowerDeductiblePercent}%:</h4>
              <div className="space-y-3 text-sm">
                <div className="grid grid-cols-2 gap-2">
                  <span className="text-muted-foreground">New deductible amount:</span>
                  <span className="font-semibold">{formatCurrency(tradeoff.lowerDeductibleAmount)}</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <span className="text-muted-foreground">Estimated new premium:</span>
                  <span className="font-semibold">{formatCurrency(tradeoff.newPremium)}/year</span>
                </div>
                <div className="grid grid-cols-2 gap-2 pt-2 border-t">
                  <span className="text-muted-foreground">Premium increase:</span>
                  <span className="font-semibold text-red-600">+{formatCurrency(tradeoff.premiumIncrease)}/year</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <span className="text-muted-foreground">Savings per claim:</span>
                  <span className="font-semibold text-green-600">{formatCurrency(tradeoff.savingsPerClaim)}</span>
                </div>
              </div>
            </div>

            <div className="p-4 bg-blue-50 dark:bg-blue-950 rounded-lg">
              <p className="font-semibold mb-2">Break-even Analysis:</p>
              {tradeoff.breakEvenYears > 0 && tradeoff.breakEvenYears < 100 ? (
                <p className="text-sm">
                  You would need to file a hurricane claim every <strong>{tradeoff.breakEvenYears.toFixed(1)} years</strong> to
                  break even on the higher premium. Since major hurricanes in any specific area typically occur less frequently,
                  <strong className="text-green-600"> keeping your current {deductiblePercent}% deductible is likely more cost-effective</strong>.
                </p>
              ) : (
                <p className="text-sm">
                  Based on these numbers, <strong className="text-green-600">your current deductible appears optimal</strong>.
                  The premium increase would exceed the deductible savings in most scenarios.
                </p>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Explanation */}
      <Card className="mb-8 bg-blue-50 dark:bg-blue-950">
        <CardHeader>
          <Info className="h-8 w-8 text-blue-600 mb-2" />
          <CardTitle>What This Means in Plain English</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <p>
            <strong>If Hurricane Ian damages your yacht:</strong> You pay the first {formatCurrency(deductibleAmount)} out of your own pocket. Insurance only starts paying once damage exceeds this amount.
          </p>
          <p>
            <strong>If damage is less than your deductible:</strong> You pay for all repairs yourself. For example, if a hurricane causes $8,000 in damage but your deductible is {formatCurrency(deductibleAmount)}, you cover the entire $8,000.
          </p>
          <p>
            <strong>If it's a total loss:</strong> You pay your {formatCurrency(deductibleAmount)} deductible, and insurance pays the remaining {formatCurrency((parseFloat(insuredValue.replace(/,/g, '')) || 0) - deductibleAmount)}.
          </p>
        </CardContent>
      </Card>

      {/* Share & Embed */}
      <div className="flex flex-wrap gap-4 justify-center mb-12">
        <Button
          variant="outline"
          onClick={() => {
            navigator.clipboard.writeText(shareUrl)
            setShowShareDialog(true)
            setTimeout(() => setShowShareDialog(false), 2000)
          }}
        >
          <Share2 className="h-4 w-4 mr-2" />
          Share Results
        </Button>
        <Button
          variant="outline"
          onClick={() => setShowEmailDialog(true)}
        >
          <Mail className="h-4 w-4 mr-2" />
          Email Results
        </Button>
        <Button
          variant="outline"
          onClick={() => setShowEmbedDialog(!showEmbedDialog)}
        >
          <Code className="h-4 w-4 mr-2" />
          Embed on Your Site
        </Button>
      </div>

      {showShareDialog && (
        <div className="fixed bottom-4 right-4 bg-green-600 text-white px-4 py-2 rounded-lg shadow-lg">
          ✓ Link copied to clipboard!
        </div>
      )}

      {showEmailDialog && (
        <Card className="mb-12 border-2 border-primary">
          <CardHeader>
            <CardTitle>Email Your Results</CardTitle>
            <CardDescription>
              Send yourself a summary of your deductible calculation
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="email-address">Email Address</Label>
              <Input
                id="email-address"
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="mt-2"
              />
            </div>
            <div className="flex gap-2">
              <Button onClick={sendEmailResults} disabled={emailSent}>
                {emailSent ? '✓ Sent!' : 'Send Email'}
              </Button>
              <Button variant="outline" onClick={() => setShowEmailDialog(false)}>
                Cancel
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              This will open your email client with a pre-filled message. No data is sent to our servers.
            </p>
          </CardContent>
        </Card>
      )}

      {showEmbedDialog && (
        <Card className="mb-12">
          <CardHeader>
            <CardTitle>Embed Code</CardTitle>
            <CardDescription>
              Copy this code to embed the calculator on your website
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
              <code>{embedCode}</code>
            </pre>
            <Button
              className="mt-4"
              onClick={() => {
                navigator.clipboard.writeText(embedCode)
              }}
            >
              Copy Embed Code
            </Button>
          </CardContent>
        </Card>
      )}

      {/* Learn More */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle>Want to Learn More?</CardTitle>
          <CardDescription>
            Read our comprehensive guide to understand how named storm deductibles work
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Link href="/learn/named-storm-deductible">
            <Button variant="outline" className="w-full sm:w-auto">
              <ExternalLink className="h-4 w-4 mr-2" />
              Read Full Guide
            </Button>
          </Link>
        </CardContent>
      </Card>

      {/* Related Pages */}
      <section className="pt-8 border-t">
        <h2 className="text-2xl font-bold mb-6">Related Resources</h2>
        <div className="grid md:grid-cols-3 gap-4">
          <Link href="/learn/agreed-value-vs-acv">
            <Card className="hover:border-primary transition-colors h-full">
              <CardHeader>
                <CardTitle className="text-lg">Agreed Value vs ACV</CardTitle>
                <CardDescription>Understand policy valuation methods</CardDescription>
              </CardHeader>
            </Card>
          </Link>
          <Link href="/learn/navigation-limits-and-layup-warranty">
            <Card className="hover:border-primary transition-colors h-full">
              <CardHeader>
                <CardTitle className="text-lg">Navigation Limits</CardTitle>
                <CardDescription>Geographic coverage restrictions</CardDescription>
              </CardHeader>
            </Card>
          </Link>
          <Link href="/yacht-insurance">
            <Card className="hover:border-primary transition-colors h-full">
              <CardHeader>
                <CardTitle className="text-lg">Yacht Insurance Guide</CardTitle>
                <CardDescription>Complete coverage overview</CardDescription>
              </CardHeader>
            </Card>
          </Link>
        </div>
      </section>
    </div>
  )
}

export default function NamedStormCalculatorPage() {
  return (
    <Suspense fallback={
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        <div className="text-center py-12">
          <Calculator className="h-12 w-12 text-primary mx-auto mb-4" />
          <p className="text-muted-foreground">Loading calculator...</p>
        </div>
      </div>
    }>
      <CalculatorContent />
    </Suspense>
  )
}
